name: Automate

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python  
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          behave features

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Check code quality
        run: |
          flake8 .
          
      

      
